system:
  lattice_vectors:            # 3x3 primitive cell vectors (Bohr)
  # Following approach in two_atom_chain.py, where the lattice is made effectively 1D by using very large lattice constants in y and z directions.
    - [5.6, 0.0, 0.0]
    - [0.0, 100.0, 0.0]
    - [0.0, 0.0, 100.0] 
  atoms:
    - symbol: H
      coords: [0.0, 0.0, 0.0]
      charge: 1.0
    - symbol: H
      coords: [2.8, 0.0, 0.0]
      charge: 1.0
    
  electron_spins: [1, 1]     
  basis: 
    H: 6-31g**
  supercell_matrix: 
    [[9, 0, 0], [0, 1, 0], [0, 0, 1]] # Following approach in two_atom_chain.py



# estimators:
#   enabled:
#     rdm: true
  
#   rdm:
#     n_sweeps: 1
#     aux_steps: 10       
#     batch_size: 2048 #This doesn't sets it, just tells the estimator the batch size to determine the size of the r' pool to generate
#     rdm_orbitals: 
#       - '0 H 1s'
#       - '1 H 1s' 
#       - '2 H 1s'
#       - '3 H 1s'
#       - '4 H 1s'
#       - '5 H 1s'
#       - '6 H 1s'
#       - '7 H 1s' 
#       - '8 H 1s'
#       - '9 H 1s'
#       - '10 H 1s'
#       - '11 H 1s'
#       - '12 H 1s'
#       - '13 H 1s' 
#       - '14 H 1s'
#       - '15 H 1s'
#       - '16 H 1s'
#       - '17 H 1s'
      

# train:
#   writers:
#     console: null
#     csv: null

#'1 H 1s    ', '1 H 2s    ', '1 H 2px   ', '1 H 2py   ', '1 H 2pz   ']
estimators:
  enabled:
    rdm_gaussian_init: true
  
  rdm_gaussian_init:
    n_sweeps: 1
    aux_steps: 10       
    batch_size: 2048 #This doesn't sets it, just tells the estimator the batch size to determine the size of the r' pool to generate
    rdm_orbitals: 
      - '8 H 1s'
      - '8 H 2s'
      - '8 H 2px'
      - '8 H 2py'
      - '8 H 2pz'


train:
  writers:
    console: null
    csv: null