system:
  lattice_vectors:            # 3x3 primitive cell vectors (Bohr)
  # Following approach in two_atom_chain.py, where the lattice is made effectively 1D by using very large lattice constants in y and z directions.
    - [7.56, 0.0, 0.0]
    - [0.0, 100.0, 0.0]
    - [0.0, 0.0, 100.0] 
  atoms:
    - symbol: H
      coords: [0.0, 0.0, 0.0]
      charge: 1.0
    - symbol: H
      coords: [3.78, 0.0, 0.0]
      charge: 1.0

  # lattice_vectors:            # 3x3 primitive cell vectors (Bohr)
  # # Following approach in two_atom_chain.py, where the lattice is made effectively 1D by using very large lattice constants in y and z directions.
  #   - [5.6, 0.0, 0.0]
  #   - [0.0, 100.0, 0.0]
  #   - [0.0, 0.0, 100.0] 
  # atoms:
  #   - symbol: H
  #     coords: [0.0, 0.0, 0.0]
  #     charge: 1.0
  #   - symbol: H
  #     coords: [2.8, 0.0, 0.0]
  #     charge: 1.0
    
  electron_spins: [1, 1]     
  basis: 
    H: cc-pvdz
  supercell_matrix: 
    [[3, 0, 0], [0, 1, 0], [0, 0, 1]] # Following approach in two_atom_chain.py

estimators:
  enabled:
    momentum_distribution: true
  
  momentum_distribution:
    N: 6 #Number of H-atoms in the supercell 
    a: 3.78 #Lattice constant of the H-chain (Bohr)

train:
  writers:
    console: null
    csv: null